### ISSUE TITLE
@compose isn't recognized in react-native

### ISSUE THREAD

**Issue by bobbybeckner** [fabiospampinato/unstated-compose#2]
Hey, love your work.  I'm trying to follow the guide in the `README` file and noticed a few things I'm curious about.

The following line:
`import {compose, ChildContainer, ParentContainer} from './compose';`

I don't see a reference to the `./compose` and I'm not sure what it contains.

I'm also getting an error, `unknown character` when I reference compose with the `@` symbol following the guide as well.

```
@compose ({
  counter: CounterContainer,
  message: MessageContainer
})
```

Lastly, without the `@` symbol, I get an error that `_Unstated.compose` is not a function.` with the library imported as `import { compose } from 'unstated-compose`.

Thanks for your contributions to Unstated!  I love this pattern so much more than Redux.

**Comment by fabiospampinato** [comment]
> I don't see a reference to the ./compose and I'm not sure what it contains.

My bad, I copied the sample code from an early version of the package and forgot to update that line. It should be `unstated-compose`.

> I'm also getting an error, unknown character when I reference compose with the @ symbol following the guide as well.

Unknown character? 🤔Maybe decorators aren't supported on your system for some reason? You can also call `compose` like this: `compose ({ foo: Foo, ... })( MyMainContainer )`, decorators are just syntactic sugar for this.

> Lastly, without the @ symbol, I get an error that _Unstated.compose is not a function.with the library imported asimport { compose } from 'unstated-compose`.

Fixed in 1.0.8, sorry about that.

> Thanks for your contributions to Unstated! I love this pattern so much more than Redux.

Yeah it seems much cleaner to me as well. I guess you lose some tooling though (no `unstated-devtools`, yet?), and making a performant complex application is much trickier with this pattern, but hopefully my plugins mostly fixed that :)
